### POST n new order
POST http://localhost:3000/api/orders
Content-Type: application/json

    {
      "id": 2,
      "name": "Horst",
      "Surname": "Frank",
      "address": {
        "street": "Ballindamm",
        "number": 1,
        "plz": 20099,
        "city": "Hamburg"
      },
      "order": "Spaghetti Bolognese",
      "sale": "16,70€"
    }

### GET all orders
GET http://localhost:3000/api/orders